# Generated by Django 3.1.2 on 2020-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripción', models.CharField(max_length=150)),
                ('costo', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
